services:
    mysql-image:
        container_name: mysql_db
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        image: mysql:8.0
        env_file: ./env/.env
        environment:
            LANG: pt_BR.UTF-8
            LC_ALL: pt_BR.UTF-8
            TZ: America/Sao_Paulo
            MYSQL_DATABASE: tutoriadb
            MYSQL_HOST: mysql-image
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - db_data:/var/lib/mysql

    django-image:
        build:
            context: ./webapi-django
            dockerfile: Dockerfile
        container_name: django_api
        command: ["./wait-for-db.sh", "mysql-image", "3306", "${MYSQL_ROOT_PASSWORD}", "python", "manage.py", "runserver", "0.0.0.0:8000"]
        volumes:
            - ./webapi-django:/app
        ports:
            - "8000:8000"
        depends_on:
            - mysql-image
        environment:
            DATABASE_HOST: 'mysql-image'
            DATABASE_PORT: '3306'
            DATABASE_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

volumes:
    db_data:
