# Generated by Django 5.2.7 on 2026-04-30 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaModel',
            fields=[
                ('id', models.AutoField(db_column='agendaId', primary_key=True, serialize=False)),
                ('horarioInicio', models.TimeField()),
                ('horarioFim', models.TimeField()),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
            ],
            options={
                'verbose_name': 'AGENDA',
                'verbose_name_plural': 'AGENDAS',
                'db_table': 'AGENDA',
            },
        ),
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.AutoField(db_column='areaId', primary_key=True, serialize=False)),
                ('nomeArea', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'AREA',
                'verbose_name_plural': 'AREAS',
                'db_table': 'AREA',
            },
        ),
        migrations.CreateModel(
            name='ConquistaModel',
            fields=[
                ('id', models.AutoField(db_column='conquistaId', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=32)),
                ('descricao', models.CharField(max_length=64)),
                ('urlImagem', models.CharField(max_length=256)),
                ('pontos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'CONQUISTA',
                'verbose_name_plural': 'CONQUISTAS',
                'db_table': 'CONQUISTA',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.AutoField(db_column='usuarioId', primary_key=True, serialize=False)),
                ('pontuacao', models.PositiveIntegerField(db_default=0, default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='senha', max_length=256)),
                ('nomePerfil', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=2)),
                ('aniversario', models.DateField(blank=True, db_default=None, default=None, null=True)),
                ('is_staff', models.BooleanField(db_default=False, default=False)),
                ('is_superuser', models.BooleanField(db_default=False, default=False)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'USUARIO',
                'verbose_name_plural': 'USUARIOS',
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='consegueModel',
            fields=[
                ('id', models.AutoField(db_column='consegueId', primary_key=True, serialize=False)),
                ('dataObtido', models.DateTimeField(auto_now_add=True)),
                ('conquistaId', models.ForeignKey(db_column='conquistaId', on_delete=django.db.models.deletion.CASCADE, to='project.conquistamodel')),
                ('usuarioId', models.ForeignKey(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consegue',
                'unique_together': {('usuarioId', 'conquistaId')},
            },
        ),
        migrations.AddField(
            model_name='conquistamodel',
            name='usuarios',
            field=models.ManyToManyField(related_name='conquistas', through='project.consegueModel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EspecialidadeModel',
            fields=[
                ('id', models.AutoField(db_column='especialidadeId', primary_key=True, serialize=False)),
                ('nomeEspecialidade', models.CharField(max_length=100)),
                ('areaId', models.ForeignKey(db_column='areaId', on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='project.areamodel')),
            ],
            options={
                'verbose_name': 'ESPECIALIDADE',
                'verbose_name_plural': 'ESPECIALIDADES',
                'db_table': 'ESPECIALIDADE',
            },
        ),
        migrations.CreateModel(
            name='ContemModel',
            fields=[
                ('id', models.AutoField(db_column='contemId', primary_key=True, serialize=False)),
                ('especialidadeId', models.ForeignKey(db_column='especialidadeId', on_delete=django.db.models.deletion.CASCADE, to='project.especialidademodel')),
            ],
            options={
                'db_table': 'contem',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoModel',
            fields=[
                ('id', models.AutoField(db_column='solicitacaoId', primary_key=True, serialize=False)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataPretendida', models.DateField()),
                ('validade', models.TimeField(null=True)),
                ('estado', models.CharField(choices=[('ACEITO', 'Solicitação Aceita'), ('PENDENTE', 'Tutor precisa aceitar'), ('RECUSADO', 'Solicitação recusada'), ('RECORRENTE', 'Solicitação recorrente')], default='PENDENTE', max_length=10)),
                ('agendaId', models.ForeignKey(db_column='agendaId', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='project.agendamodel')),
                ('areaId', models.ForeignKey(db_column='areaId', on_delete=django.db.models.deletion.CASCADE, to='project.areamodel')),
                ('especialidadeId', models.ForeignKey(db_column='especialidadeId', on_delete=django.db.models.deletion.CASCADE, to='project.especialidademodel')),
                ('usuarioId', models.ForeignKey(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOLICITACAO',
                'verbose_name_plural': 'SOLICITACOES',
                'db_table': 'SOLICITACAO',
                'unique_together': {('usuarioId', 'agendaId')},
            },
        ),
        migrations.CreateModel(
            name='TutorModel',
            fields=[
                ('id', models.AutoField(db_column='tutorId', primary_key=True, serialize=False)),
                ('usuarioId', models.OneToOneField(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TUTOR',
                'verbose_name_plural': 'TUTORES',
                'db_table': 'TUTOR',
            },
        ),
        migrations.CreateModel(
            name='SessaoModel',
            fields=[
                ('id', models.AutoField(db_column='sessaoId', primary_key=True, serialize=False)),
                ('dataRealizacao', models.DateField()),
                ('agendaId', models.ForeignKey(db_column='agendaId', on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='project.agendamodel')),
                ('areaId', models.ForeignKey(db_column='areaId', on_delete=django.db.models.deletion.CASCADE, to='project.areamodel')),
                ('especialidadeId', models.ForeignKey(db_column='especialidadeId', on_delete=django.db.models.deletion.CASCADE, to='project.especialidademodel')),
                ('usuarioId', models.ForeignKey(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
                ('solicitacaoId', models.ForeignKey(db_column='solicitacaoId', on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='project.solicitacaomodel')),
                ('tutorId', models.ForeignKey(db_column='tutorId', on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='project.tutormodel')),
            ],
            options={
                'verbose_name': 'SESSAO',
                'verbose_name_plural': 'SESSOES',
                'db_table': 'SESSAO',
            },
        ),
        migrations.AddField(
            model_name='especialidademodel',
            name='tutores',
            field=models.ManyToManyField(related_name='especialidades', through='project.ContemModel', to='project.tutormodel'),
        ),
        migrations.AddField(
            model_name='contemmodel',
            name='tutorId',
            field=models.ForeignKey(db_column='tutorId', on_delete=django.db.models.deletion.CASCADE, to='project.tutormodel'),
        ),
        migrations.AddField(
            model_name='agendamodel',
            name='tutorId',
            field=models.ForeignKey(db_column='tutorId', on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='project.tutormodel'),
        ),
        migrations.AlterUniqueTogether(
            name='especialidademodel',
            unique_together={('areaId', 'nomeEspecialidade')},
        ),
        migrations.AlterUniqueTogether(
            name='contemmodel',
            unique_together={('especialidadeId', 'tutorId')},
        ),
        migrations.AlterUniqueTogether(
            name='agendamodel',
            unique_together={('tutorId', 'dia', 'horarioInicio')},
        ),
    ]
