# Generated by Django 5.2.7 on 2025-10-23 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.AutoField(db_column='conquistaId', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=32)),
                ('descricao', models.CharField(max_length=64)),
                ('urlImagem', models.CharField(max_length=256)),
                ('pontos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'CONQUISTA',
                'verbose_name_plural': 'CONQUISTAS',
                'db_table': 'CONQUISTA',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='usuarioId', primary_key=True, serialize=False)),
                ('pontuacao', models.PositiveIntegerField(db_default=0, default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='senha', max_length=256)),
                ('nomePerfil', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=2)),
                ('urlFoto', models.URLField(max_length=256, db_default='', default='')),
                ('aniversario', models.DateField()),
                ('is_staff', models.BooleanField(db_default=False, default=False)),
                ('is_superuser', models.BooleanField(db_default=False, default=False)),
                ('is_active', models.BooleanField(db_default=False, default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'USUARIO',
                'verbose_name_plural': 'USUARIOS',
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='consegue',
            fields=[
                ('id', models.AutoField(db_column='consegueId', primary_key=True, serialize=False)),
                ('dataObtido', models.DateTimeField()),
                ('conquistaId', models.ForeignKey(db_column='conquistaId', on_delete=django.db.models.deletion.CASCADE, to='project.conquista')),
                ('usuarioId', models.ForeignKey(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consegue',
                'unique_together': {('usuarioId', 'conquistaId')},
            },
        ),
        migrations.AddField(
            model_name='conquista',
            name='usuarios',
            field=models.ManyToManyField(related_name='conquistas', through='project.consegue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(db_column='tutorId', primary_key=True, serialize=False)),
                ('usuarioId', models.OneToOneField(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TUTOR',
                'verbose_name_plural': 'TUTORES',
                'db_table': 'TUTOR',
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(db_column='sessaoId', primary_key=True, serialize=False)),
                ('horarioInicio', models.TimeField()),
                ('horarioFim', models.TimeField()),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('tutorId', models.ForeignKey(db_column='tutorId', on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='project.tutor')),
            ],
            options={
                'verbose_name': 'SESSAO',
                'verbose_name_plural': 'SESSOES',
                'db_table': 'SESSAO',
                'unique_together': {('tutorId', 'horarioInicio', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(db_column='solicitacaoId', primary_key=True, serialize=False)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateTimeField(null=True)),
                ('estado', models.CharField(choices=[('ACEITO', 'Solicitação Aceita'), ('PENDENTE', 'Tutor precisa aceitar'), ('RECUSADO', 'Solicitação recusada'), ('RECORRENTE', 'Solicitação recorrente')], max_length=10)),
                ('sessaoId', models.ForeignKey(db_column='sessaoId', on_delete=django.db.models.deletion.CASCADE, to='project.sessao')),
                ('usuarioId', models.ForeignKey(db_column='usuarioId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SOLICITACAO',
                'unique_together': {('usuarioId', 'sessaoId')},
            },
        ),
    ]
